name: Update domains

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install

      - run: npm run update

      - run: git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --local user.name "github-actions[bot]"
      - run: 'git commit -a -m "feat: Updated domains" || echo "No changes to commit"'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
