name: Build/Deploy on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install && npx camoufox-js fetch

      - run: npm run update
      - run: npm run lint
      - run: npm run build
      # - run: npm test

      - uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./dist/package.json
